name: CI

on: workflow_dispatch

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        fleet: [text_html/midi-synthesizer, text_html/midi-synthesizer64]

    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://github.com
    steps:
      - uses: actions/checkout@v6

      - name: install balena cli
        run: |
          wget --no-verbose -O balena-cli.zip "https://github.com/balena-io/balena-cli/releases/download/${BALENA_VERSION}/balena-cli-${BALENA_VERSION}-linux-x64-standalone.zip"
          unzip balena-cli.zip
        env:
          BALENA_VERSION: v20.0.9

      - name: login to balena
        run: balena-cli/balena login --token "$BALENA_API_KEY"
        env:
          BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}

      - name: deploy fleet
        run: balena-cli/balena push --source "$GITHUB_WORKSPACE" "${{ matrix.fleet }}"
        env:
          BALENA_FLEET: ${{ matrix.fleet }}
